### ISSUE TITLE
Sass commands reported as error by the language server

### ISSUE THREAD

**Issue by bfulop** [veonim/ext-css#1]
Continued from here : https://github.com/veonim/veonim/issues/416

The langserver does work with the last update of `veonim/ext-css` but the I'm getting a lot of strange linting errors:

<img width="354" alt="sass-linting-errors" src="https://user-images.githubusercontent.com/1718128/42731474-3547790c-880e-11e8-829b-bc9704477199.png">

Don't know if this should be reported at the language server repo or here?

BTW I saw another CSS/SASS/LESS langserver repo here : https://github.com/vscode-langservers/vscode-css-languageserver-bin 
Cannot say if it's superior to the Microsoft maintained one. This one is used in Oni and works pretty good as far as I can tell. No workspace symbol completions though.

**Comment by bfulop** [comment]
Ok I think doing `autocmd BufEnter *.scss set ft=sass` is resolving the issue

**Comment by breja** [comment]
Actually we are using the same language server as VSCode and Oni. If Oni and VSCode work fine, then the issue is probably in Veonim. 

In this case, the issue was with Veonim. The `scss` or `less` language ids were not getting passed down to the language server, thus the language server defaulting and operating in `css` mode.

The fix for that described here: https://github.com/veonim/veonim/issues/426

With `filetype` == `scss` and the fix from https://github.com/veonim/veonim/issues/426:
<img width="289" alt="screen shot 2018-07-15 at 4 04 42 pm" src="https://user-images.githubusercontent.com/2581815/42738106-3e8d37fc-884c-11e8-85f6-3a1fd12791e5.png">

Let me know if that does not work and I will investigate further.

**Comment by bfulop** [comment]
Works great now, thanks for fixing it so quickly!
